### PR TITLE
Adding unit test cases to increase code coverage

### PR DESCRIPTION
**Pull request by REETI-SARUP**
## What's changing
For Issue #5, Added unit test cases to increase code coverage of extension/src/components/Header.jsx

## Checklist

[x] Unit tests (updated and/or added)
[ ] Documentation (function/class docs, comments, etc.)

Published PR with canary version: `1.0.1-canary.13.112.0`

### CODE REVIEW

**Comment by Celeo** [comment]
Thanks for contributing the PR! We'll have a look soon.

**Comment by REETI-SARUP** [comment]
> Thanks for contributing the PR! We'll have a look soon.

Sure, thanks

**Review by TimClarkson — APPROVED** [review]
Looks good!  Thanks for the help!

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in v1.0.1 :rocket:

**Pull request merged**
